spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/mercadolivro?createDatabaseIfNotExist=true
    username: root
    password: root
  jackson:
    default-property-inclusion: non_null

jwt:
  secret: 2dee69c2-1b5a-4cd5-bf3b-9ae1f76ff5c7
  expiration: 999999

flyway:
  url: jdbc:mysql://localhost:3306/mercadolivro
  schemas: mercadolivro
  enable: true
  validate-on-migrate: true
  baseline-on-migrate: true
  baseline-version: 0

